### ISSUE TITLE
Failed building wheel for ztpserver while running 'pip install ztpserver --upgrade'

### ISSUE THREAD

**Issue by advornic** [arista-eosplus/ztpserver#326]
Building wheels for collected packages: ztpserver
  Running setup.py bdist_wheel for ztpserver
  Complete output from command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-awH9eJ/ztpserver/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))"\
 bdist_wheel -d /tmp/tmpzibwlDpip-wheel-:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-awH9eJ/ztpserver/setup.py", line 153, in <module>
      data_files=data_files
    File "/usr/lib64/python2.7/distutils/core.py", line 138, in setup
      ok = dist.parse_command_line()
    File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 232, in parse_command_line
      result = _Distribution.parse_command_line(self)
    File "/usr/lib64/python2.7/distutils/dist.py", line 467, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 558, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
    File "/usr/lib64/python2.7/distutils/dist.py", line 523, in _parse_command_opts
      cmd_class = self.get_command_class(command)
    File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 362, in get_command_class
      ep.require(installer=self.fetch_build_egg)
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2364, in require
      reqs = self.dist.requires(self.extras)
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2596, in requires
      dm = self._dep_map
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2797, in _dep_map
      self.__dep_map = self._compute_dependencies()
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2830, in _compute_dependencies
      common = frozenset(reqs_for_extra(None))
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2827, in reqs_for_extra
      if req.marker_fn(override={'extra':extra}):
    File "/usr/lib/python2.7/site-packages/_markerlib/markers.py", line 109, in marker_fn
      return eval(compiled_marker, environment)
    File "<environment marker>", line 1, in <module>
  NameError: name 'sys_platform' is not defined

  ----------------------------------------
  Failed building wheel for ztpserver
Failed to build ztpserver

**Comment by advornic** [comment]
sudo pip install setuptools --upgrade

will fix this.
